AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BedrockBot

  Sample SAM Template for BedrockBot
Resources:
  OGMonolithFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - bedrock:*
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
      Environment:
        Variables:
          BOT_TOKEN: 8073759396:AAFZQOzXGsyc6VZ90ZKUp5gzohj8TYqG0MU
          BUCKET_NAME: !Ref S3Bucket

  ConfigSetterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: setConfig.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Environment:
        Variables:
          BOT_TOKEN: 8073759396:AAFZQOzXGsyc6VZ90ZKUp5gzohj8TYqG0MU 
          BUCKET_NAME: !Ref S3Bucket          

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['',[!Ref 'AWS::AccountId','-bedrockstore-',!Ref 'AWS::Region']]

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  OGMonolithFunctionArn:
    Description: Monolith Function ARN
    Value: !GetAtt OGMonolithFunction.Arn
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
